name: ghostsandmachines
url: "https://ghostsandmachines.github.io"
baseurl: ""
description: This is the best website ever in the history of all website and no website will ever be able to top this incredible display of wit, wisdom, strength and, why not, sexiness. Unfortunately, it's a work-in-progress for now.
author:
  name: Ghosts and Machines
  email: "ghostsandmachines@yahoo.com.au"  
title: Ghosts And Machines
markdown: kramdown
theme: minima
exclude: ['README.md']
