name: ghostsandmachines
email: "ghostsandmachines@yahoo.com"
url: "https://ghostsandmachines.github.io"
baseurl: "" 
description: The best website ever made that will ever be made. Unfortunately, it's currently unavailable.
title: Ghosts And Machines
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
disqus: 
  shortname: ghostsandmachines
exclude: ['README.md', 'code_tmp.md']
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

#it looks like putting 
#author: 
#       name:
#       email:
#stopss the build. weird, given that this is how many set it up, you should look into it.

#baseurl would all that is after github.io, for instance /sitename. We want to use the url as the sitename, so no changes.

#description works and no, it does not conflict with the description of the repository, this is the description of the website.
#the problem seemed to be the author thing.


