name: ghostsandmachines
title: Ghosts And Machines
markdown: kramdown
baseurl: /ghostsandmachines.github.io/
permalink: /blog/:year/:month/:day/:title 
plugins:
  - jekyll-archives
jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layout: 
    year: archive-year
    month: archive-month
    day: archive-day
    tag: archive-tags
  permalinks:
    year: '/archive/year/:year/'
    month: '/archive/month/:year-:month/'
    day: '/archive/day/:year-:month-:day/'
    tag: '/archive/tags/:name/'
